name: CI
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: linters
        run: |
          npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Transfer build files to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: 95.163.212.121
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: "dist/*"
          target: "/var/www/findfreelancer.ru/2021_1_BERM/dist"
          strip_components: 1
          rm: true