name: CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: |
          sudo apt install nodejs
          sudo apt install npm
          npm install
      - name: linters
        run: |
          npm run lint

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 95.163.212.121
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: ./deploy_front.sh